services:
  db:
    image: postgres:16
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PORT: ${DB_PORT}
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    command: bash -c "poetry run alembic upgrade head && poetry run python -m uvicorn backend.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "9000:80"
    depends_on:
      - backend
